### ISSUE TITLE
CSV file dumping the info about the tools

### ISSUE THREAD

**Issue by criscod** [hay/wiki-tools#53]
First of all, thanks for curating this list of tools! It's very useful to have an overview of all existing tools. 

Would it be possible to have in the [site](https://tools.wmflabs.org/hay/directory/) a button to be able to download an up-to-date CSV file with the information displayed (i.e., title, description, author, URL and tags)?

**Comment by hay** [comment]
There's no CSV file available because some of the information has more than two dimensions (like the tags). However, there is a hidden API that will give you back a JSON file with all of the data. It's pretty to transform that to a CSV. 

https://tools.wmflabs.org/hay/directory/api.php

I've added a link to that API on the directory page as well. 

Thanks for reporting this issue.
